# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          
      - name: Install dependencies
        run: cd change_app && flutter pub get

      - name: Build Web
        run: cd change_app && flutter build web --release

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: change_app/build/web
          
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.0.10
        with:
          # Should this action only emit build telemetry instead of deploying the build artifact?
          emit_telemetry: true
          # GitHub token
          token: ${{ github.token }}
          path: change_app/build/web

      
      
